/**
 * Memorable bot name generator for Literati card game bots.
 *
 * The pool is intentionally small and distinctive so players can quickly
 * remember who has which card during play.
 *
 * Bot IDs always start with "bot_" so the server can gate them separately.
 */

export const BOT_NAME_KEYS: readonly string[] = [
  "ziggy",
  "mochi",
  "nova",
  "tango",
  "pebble",
  "echo",
  "jinx",
  "vega",
] as const;

export type BotName = string;

/**
 * Generate a deterministic integer hash from a seed string.
 */
function seedHash(seed: string): number {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) {
    const char = seed.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash; // 32-bit integer
  }
  return Math.abs(hash);
}

/**
 * Generate a memorable bot name key.
 *
 * @param seed - Optional seed for deterministic output. If omitted, random.
 * @returns e.g. "ziggy" or "vega"
 */
export function generateBotName(seed?: string): BotName {
  let index: number;

  if (seed !== undefined) {
    const hash = seedHash(seed);
    index = hash % BOT_NAME_KEYS.length;
  } else {
    index = Math.floor(Math.random() * BOT_NAME_KEYS.length);
  }

  return BOT_NAME_KEYS[index];
}

/**
 * Convert a raw bot name key to a human-readable display name.
 * "ziggy" → "Ziggy"
 * "nova_2" → "Nova 2"
 */
export function formatBotName(name: BotName): string {
  return name
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

/**
 * Return true when a name was auto-generated by this system.
 */
export function isBotName(name: string): boolean {
  return (BOT_NAME_KEYS as readonly string[]).includes(name.toLowerCase());
}

/**
 * Generate N unique bot names, avoiding existing ones.
 */
export function generateUniqueBotNames(
  count: number,
  existingNames: string[] = []
): BotName[] {
  const taken = new Set(existingNames);
  const names: BotName[] = [];
  let attempts = 0;
  const maxAttempts = count * 50;

  while (names.length < count && attempts < maxAttempts) {
    const name = generateBotName();
    if (!taken.has(name)) {
      taken.add(name);
      names.push(name);
    }
    attempts++;
  }

  // Fallback: suffix with a counter
  let suffix = 2;
  while (names.length < count) {
    const base = generateBotName();
    const suffixed = `${base}_${suffix}`;
    if (!taken.has(suffixed)) {
      taken.add(suffixed);
      names.push(suffixed);
    }
    suffix++;
  }

  return names;
}
